export const FACEBOOK_OPTIMIZATION_GOAL_ID_APP_INSTALL = '13';
export const FACEBOOK_OPTIMIZATION_GOAL_ID_VALUE = '25';
export const FACEBOOK_OPTIMIZATION_GOAL_ID_APP_EVENTS = '0';
export const OPTIMIZATION_GOAL_ID_TO_DISPLAY_EVENTS = '0';
